name: iOS CI

on:
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: macos-latest

    strategy:
      matrix:
        simulator: [ "iPhone 17", "iPad Pro 13-inch (M5)" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.3.0'

      - name: Run Unit Tests
        run: |
          cd ios
          set -o pipefail
          xcodebuild test -project News.xcodeproj -scheme News \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=${{ matrix.simulator }}" \
            -only-testing:NewsTests | xcpretty

      - name: Run UI Tests
        run: |
          cd ios
          set -o pipefail
          xcodebuild test -project News.xcodeproj -scheme News \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=${{ matrix.simulator }}" \
            -only-testing:NewsUITests | xcpretty
