name: iOS CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    strategy:
      matrix:
        simulator: [ "iPhone 15", "iPad Pro (12.9-inch) (6th generation)" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v2
        with:
          xcode-version: '15.0'

      - name: Install dependencies
        run: |
          brew install cocoapods || true
          cd ios/PROJECT && pod install --repo-update

      - name: Build
        run: |
          cd ios/PROJECT
          xcodebuild -workspace News.xcworkspace -scheme News -sdk iphonesimulator -destination "platform=iOS Simulator,name=${{ matrix.simulator }}" clean build | xcpretty

      - name: Run Unit Tests
        run: |
          cd ios/PROJECT
          xcodebuild test -workspace News.xcworkspace -scheme News -sdk iphonesimulator -destination "platform=iOS Simulator,name=${{ matrix.simulator }}" -only-testing:NewsTests | xcpretty

      - name: Run UI Tests
        run: |
          cd ios/PROJECT
          xcodebuild test -workspace News.xcworkspace -scheme NewsUITests -sdk iphonesimulator -destination "platform=iOS Simulator,name=${{ matrix.simulator }}" | xcpretty
